# Build Consul Server Container
FROM {{ dockerUser + "/" + buildImageName + ":" + buildImageVersion }}
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"
USER root

ARG OPENJDK_VERSION={{ finalImageVersion }} \
    JAVA_HOME=/usr/lib/jvm/default-jvm/jre

# Install OpenJDK
# hadolint ignore=SC2046,DL3018,DL4006
RUN echo "http://nl.alpinelinux.org/alpine/v$(cut -d. -f1-2 /etc/alpine-release)/community/" >> /etc/apk/repositories && \
    apk --update --no-cache add openjdk$(echo ${OPENJDK_VERSION} | cut -d. -f1)=${OPENJDK_VERSION}-r1 nss

USER ${ALPINE_USER}
